#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NmFhMjhhMzM1YmFmNzg1MmViMjVmMmJjNjlhNjQ5MmRlMjI0N2VjMTY0ZWU2ZTlkMDAzMDA5YjliNDQ5YmRkNWFmZDQ4MTAyNzFmZGEzYThlMzUwOTFjNDc2NzFjMzRhNTI1OA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
